// <auto-generated />
using System;
using HotelSystem_EF.Dal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelSystem_EF.Api.Migrations
{
    [DbContext(typeof(HotelSystemContext))]
    [Migration("20230607155947_seedingData")]
    partial class seedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelSystem_EF.Dal.Models.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("Id");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description 1",
                            Name = "Amenity 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description 2",
                            Name = "Amenity 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description 3",
                            Name = "Amenity 3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description 4",
                            Name = "Amenity 4"
                        });
                });

            modelBuilder.Entity("HotelSystem_EF.Dal.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckInDate = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2023, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CheckInDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CheckInDate = new DateTime(2023, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2023, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CheckInDate = new DateTime(2023, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 4,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("HotelSystem_EF.Dal.Models.BookingService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ServiveId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ServiveId");

                    b.ToTable("BookingServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingId = 1,
                            Quantity = 2,
                            ServiveId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookingId = 2,
                            Quantity = 1,
                            ServiveId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookingId = 3,
                            Quantity = 3,
                            ServiveId = 3
                        },
                        new
                        {
                            Id = 4,
                            BookingId = 4,
                            Quantity = 2,
                            ServiveId = 4
                        });
                });

            modelBuilder.Entity("HotelSystem_EF.Dal.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100.0,
                            BookingId = 1,
                            PaymentDate = new DateTime(2023, 6, 7, 18, 59, 47, 683, DateTimeKind.Local).AddTicks(4060)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 150.0,
                            BookingId = 2,
                            PaymentDate = new DateTime(2023, 6, 7, 18, 59, 47, 683, DateTimeKind.Local).AddTicks(4103)
                        },
                        new
                        {
                            Id = 3,
                            Amount = 200.0,
                            BookingId = 3,
                            PaymentDate = new DateTime(2023, 6, 7, 18, 59, 47, 683, DateTimeKind.Local).AddTicks(4106)
                        },
                        new
                        {
                            Id = 4,
                            Amount = 120.0,
                            BookingId = 4,
                            PaymentDate = new DateTime(2023, 6, 7, 18, 59, 47, 683, DateTimeKind.Local).AddTicks(4109)
                        });
                });

            modelBuilder.Entity("HotelSystem_EF.Dal.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ReviewDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Great experience!",
                            Rating = 4.5,
                            ReviewDate = new DateTime(2023, 6, 7, 18, 59, 47, 683, DateTimeKind.Local).AddTicks(4753),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Average service",
                            Rating = 3.7999999999999998,
                            ReviewDate = new DateTime(2023, 6, 7, 18, 59, 47, 683, DateTimeKind.Local).AddTicks(4766),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Highly recommended!",
                            Rating = 5.0,
                            ReviewDate = new DateTime(2023, 6, 7, 18, 59, 47, 683, DateTimeKind.Local).AddTicks(4770),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Disappointing stay",
                            Rating = 2.5,
                            ReviewDate = new DateTime(2023, 6, 7, 18, 59, 47, 683, DateTimeKind.Local).AddTicks(4773),
                            UserId = 4
                        });
                });

            modelBuilder.Entity("HotelSystem_EF.Dal.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 100.0,
                            RoomNumber = 101,
                            RoomType = "Standard",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Price = 150.0,
                            RoomNumber = 102,
                            RoomType = "Deluxe",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Price = 100.0,
                            RoomNumber = 201,
                            RoomType = "Standard",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Price = 150.0,
                            RoomNumber = 202,
                            RoomType = "Deluxe",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("HotelSystem_EF.Dal.Models.RoomAmenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmenityId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AmenityId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomAmenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmenityId = 1,
                            RoomId = 1
                        },
                        new
                        {
                            Id = 2,
                            AmenityId = 2,
                            RoomId = 2
                        },
                        new
                        {
                            Id = 3,
                            AmenityId = 3,
                            RoomId = 3
                        },
                        new
                        {
                            Id = 4,
                            AmenityId = 4,
                            RoomId = 4
                        });
                });

            modelBuilder.Entity("HotelSystem_EF.Dal.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description 1",
                            Price = 10.99,
                            ServiceName = "Service 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description 2",
                            Price = 15.99,
                            ServiceName = "Service 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description 3",
                            Price = 20.989999999999998,
                            ServiceName = "Service 3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description 4",
                            Price = 25.989999999999998,
                            ServiceName = "Service 4"
                        });
                });

            modelBuilder.Entity("HotelSystem_EF.Dal.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "password1",
                            RoomId = 1,
                            Username = "johndoe"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            Password = "password2",
                            RoomId = 2,
                            Username = "janesmith"
                        },
                        new
                        {
                            Id = 3,
                            Email = "mike.johnson@example.com",
                            FirstName = "Mike",
                            LastName = "Johnson",
                            Password = "password3",
                            RoomId = 3,
                            Username = "mikejohnson"
                        },
                        new
                        {
                            Id = 4,
                            Email = "sarah.williams@example.com",
                            FirstName = "Sarah",
                            LastName = "Williams",
                            Password = "password4",
                            RoomId = 4,
                            Username = "sarahwilliams"
                        });
                });

            modelBuilder.Entity("HotelSystem_EF.Dal.Models.Booking", b =>
                {
                    b.HasOne("HotelSystem_EF.Dal.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelSystem_EF.Dal.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelSystem_EF.Dal.Models.BookingService", b =>
                {
                    b.HasOne("HotelSystem_EF.Dal.Models.Booking", "Booking")
                        .WithMany("BookingServices")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelSystem_EF.Dal.Models.Service", "Service")
                        .WithMany("BookingServices")
                        .HasForeignKey("ServiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HotelSystem_EF.Dal.Models.Payment", b =>
                {
                    b.HasOne("HotelSystem_EF.Dal.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("HotelSystem_EF.Dal.Models.Review", b =>
                {
                    b.HasOne("HotelSystem_EF.Dal.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelSystem_EF.Dal.Models.Room", b =>
                {
                    b.HasOne("HotelSystem_EF.Dal.Models.User", "User")
                        .WithOne("Room")
                        .HasForeignKey("HotelSystem_EF.Dal.Models.Room", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelSystem_EF.Dal.Models.RoomAmenity", b =>
                {
                    b.HasOne("HotelSystem_EF.Dal.Models.Amenity", "Amenity")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelSystem_EF.Dal.Models.Room", "Room")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelSystem_EF.Dal.Models.Amenity", b =>
                {
                    b.Navigation("RoomAmenities");
                });

            modelBuilder.Entity("HotelSystem_EF.Dal.Models.Booking", b =>
                {
                    b.Navigation("BookingServices");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("HotelSystem_EF.Dal.Models.Room", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("RoomAmenities");
                });

            modelBuilder.Entity("HotelSystem_EF.Dal.Models.Service", b =>
                {
                    b.Navigation("BookingServices");
                });

            modelBuilder.Entity("HotelSystem_EF.Dal.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");

                    b.Navigation("Room")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
