// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Online_Musical_Equipment_Shop_DAL.Context;

#nullable disable

namespace Online_Musical_Equipment_Shop_API.Migrations
{
    [DbContext(typeof(MusicalEquipmentShopContext))]
    [Migration("20230605101308_InitialDatabase")]
    partial class InitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Online_Musical_Equipment_Shop_DAL.Entities.Categories", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d1c2c48-5fe5-48ed-8cd2-2b723a4270f3"),
                            CategoryTitle = "Guitars"
                        },
                        new
                        {
                            Id = new Guid("658a0961-3114-48e0-9422-17b79861d2b7"),
                            CategoryTitle = "Keyboards"
                        },
                        new
                        {
                            Id = new Guid("21b15c35-ddf6-41a4-a632-700aee480598"),
                            CategoryTitle = "Drums"
                        },
                        new
                        {
                            Id = new Guid("f5e50e3b-f1bf-4c1d-a520-489e31f981e0"),
                            CategoryTitle = "Strings"
                        },
                        new
                        {
                            Id = new Guid("a6eddd97-242c-4cc8-ae78-7936efd0c38f"),
                            CategoryTitle = "Winds"
                        },
                        new
                        {
                            Id = new Guid("0bbed2e8-d0c7-4f8c-8af8-2a621c6ccf4b"),
                            CategoryTitle = "Percussion"
                        },
                        new
                        {
                            Id = new Guid("4608485b-e6b1-4d01-a611-680f1411779e"),
                            CategoryTitle = "Amplifiers"
                        },
                        new
                        {
                            Id = new Guid("8226cf9f-5e88-4136-a183-aef595b8a8a4"),
                            CategoryTitle = "Accessories"
                        },
                        new
                        {
                            Id = new Guid("85284a17-8f07-487e-9e6d-1016426a8709"),
                            CategoryTitle = "DJEquipment"
                        },
                        new
                        {
                            Id = new Guid("e6c6ae21-9dec-4221-b4b9-170797ba007b"),
                            CategoryTitle = "RecordingEquipment"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
